### ISSUE TITLE
Practica 3 ej 2 esta mal

### ISSUE THREAD

**Issue by faustomartinez** [yagopajarino/uba-algebraI#10]
U={n e N/ n<=1000}
M3={n e U/ n es multiplo de 3}
M5={n e U/ n es multiplo de 5}
Queremos calcular #(M3 u M5)^c (el cardinal del complemento de la union)
La interseccion entre ambos es M15={n e U/ n es multiplo de 5}
Sabemos que #M3=333 (1000/3), #M5=200 (1000/5) y #M15=66 (1000/15)
Luego el cardinal de la union #(M3 u M5) es #M3 + #M5 - #M15(interseccion de ambos) = 333+200-66 = 467 multiplos de 3 o 5
Luego para calcular los que no lo son, calculamos el cardinal del complemento
#(M3 u M5)^c = #U - #(M3 u M5) = 1000-467= 533

**Comment by yagopajarino** [comment]
Corregido! Graciassss

**Comment by faustomartinez** [comment]
😀👍
