### ISSUE TITLE
Problema en 4.2.B. pregunta ii

### ISSUE THREAD

**Issue by Sturm0** [yagopajarino/uba-algebraI#14]
En las respuestas del repo dice que da n=2. Sin embargo llegue a:
![4 2 B  pregunta ii](https://github.com/yagopajarino/uba-algebraI/assets/89245373/3a6d184d-b51a-479d-8121-22cfcb96fea0)
¿Metí la pata en algo o hay un problema en el pdf?

**Comment by yagopajarino** [comment]
Hola! Tenés razón, habia un error en el pdf. Ya lo corregí. Gracias por el aporte!

**Comment by yagopajarino** [comment]
https://github.com/yagopajarino/uba-algebraI/commit/fe40e1714df18c7ea442cf4cd0e3640323f30eb3
