### ISSUE TITLE
Práctica 3

### ISSUE THREAD

**Issue by fkrause98** [yagopajarino/uba-algebraI#8]
Hola, me parece que hay un ejercicio de la práctica 3 que no estás planteados correctamente.
### Punto 1:
Entiendo que la idea de usar complemento es correcta, pero la forma de contar anagramas no.
En total, hay `(10!)/(3!*2!) ` anagramas y hay `(9!/3!)` anagramas donde las i están juntas.
Yo desprendo mi razonamiento del ejemplo 15 este apunte de combinatoria [este apunte de combinatoria](https://cms.dm.uba.ar/academico/materias/2docuat2015/algebra_I/Combinatoria-Puddu.pdf).

Entonces, contar los anagramas totales sale así:
Ubico la P: Comb(10, 1)
Ubico las O: Comb(9, 3)
Ubico la L: Comb(6,1)
Ubico las I: Comb(5,2)
Ubico la N: Comb(3,1)
Ubico la M: Comb(2,1)
Ubico la S: Comb(1,1)
Esto se reduce a `(10!)/(3!*2!)`

Para contar los anagramas donde las 2 i están juntas, las contamos como
una sola letra, por lo que tenemos 9 en total y la cuenta nos queda
 como dije arriba:  `(9!/3!)`
 
 Así, la cuenta total es  `(10!)/(3!*2!)` - `(9!/3!)`
 
 Ojo, quizás lo estoy pensando mal yo!
 
 Por cierto, alto laburo el de las guías, muchas gracias 😄.

**Comment by yagopajarino** [comment]
Completamente de acuerdo con tu razonamiento. Ya quedó corregido. 
Muchas gracias por el aporte :)
